version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:12"
      timezone: "Europe/Berlin"
    assignees:
      - "timokramer"
    commit-message:
      prefix: "[image:update] "
    target-branch: "clj-tools"
