version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.4

jobs:
  publish-increment:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Check for skip-release flag
          command: |
            if ! git log -1 --pretty=%B | grep -q '\[semver:patch\]'; then
              echo "[semver:patch] flag not found, skipping publish"
              circleci-agent step halt
            fi
      - run:
          name: Install CircleCI CLI
          command: |
            URL=https://raw.githubusercontent.com
            URL=$URL/CircleCI-Public/circleci-cli/main/install.sh
            curl -fLSs $URL | sudo bash
      - run:
          name: Pack orb
          command: circleci orb pack src > orb.yml
      - run:
          name: Publish incremented version
          command: |
            circleci orb publish increment orb.yml \
              replikativ/clj-tools patch --token $CIRCLE_TOKEN

workflows:
  lint-pack-publish:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - publish-increment:
          context: orb-deploy
          requires:
            - orb-tools/pack
          filters:
            branches:
              only: clj-tools
