description: |
  Build a jar with depstar for deployment to Clojars.
executor: clojurecli
parameters:
  build_cljs:
    type: boolean
    default: false
steps:
  - attach_workspace:
      at: /home/circleci
  - run:
      name: clean
      command: clojure -T:build clean
  - run:
      name: jar
      command: clojure -T:build jar
  - when:
      condition: <<parameters.build_cljs>>
      steps:
        - run:
            name: compile_cljs
            command: npx shadow-cljs compile ci
            no_output_timeout: 5m
  - persist_to_workspace:
      root: /home/circleci/
      paths:
        - .m2
        - .npm
        - replikativ
